name: github pages

on:
  push:
    branches: [ master, main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find Tag
        id: tagger
        uses: jimschubert/query-tag-action@v1
        with:
          include: 'v*'

      - name: Set env
        run: |
          echo "git_hash=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
          echo "git_branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.0"

      - name: Get yarn cache
        id: yarn-cache
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-website-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-website-

      - run: yarn install
      - run: yarn build
        env:
          VUE_APP_GIT_BRANCH: ${{ env.git_branch }}
          VUE_APP_GIT_TAG: ${{ steps.tagger.outputs.tag }}
          VUE_APP_GIT_SHA: ${{ env.git_hash }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          cname: dev.robonomics.app
